corpus:
  path14A_html: ../data/14A/
  path14A_frag: ../data/14A_frags/
  path14A_meta: ../data/14A_meta/

kendra:
  index_id: [YOUR KENDRA INDEX ID]
  region_name: us-east-1
  data_source: s3://genaiconf-[YOUR S3 ID]

aos:
 aos_host: [YOUR OPENSEARCH DOMAIN ENDPOINT]
 aos_index: workshop-demo-knn

llm:
  t5_endpoint: jumpstart-dft-hf-text2text-flan-t5-xl
  embedding_endpoint: jumpstart-dft-hf-textembedding-gpt-j-6b-fp16
